# Example config file 

redundancy = 2
core_ann_interval = 10
beacon_interval = 5
cache_size = 5000

[host]
id = 1
uri = "tcp://localhost:1881"

[[neighbors]]
id = 2
uri = "tcp://localhost:1882"

[[neighbors]]
id = 4
uri = "tcp://localhost:1884"
